package comrade:hypervisor@0.1.0;

interface check {
  /// Checks the signature
  signature: func(key: string) -> bool;

  /// Checks the hash preimage 
  preimage: func(key: string) -> bool;
}

interface stack {
  /// Pushes the value associated with the key-path onto the parameter stack.
  push: func(key: string);

  /// Pops the top value off of the parameter stack.
  pop: func() -> string;
}

/// Tracing for logging events
interface tracing {
    /// Send an event to the host
    send-event: func(event: list<u8>);
}

/// An example world for the component to target.
world example {

    /// Allow guest code to call tracing functions interface from the host
    import tracing;

    /// Allow consumer to call check functions interface
    export check;

    /// Allow consumer to call stack functions interface
    export stack;
}
