package component:vm;

interface vm {
    /// Runs the script 
    run: func(script: string) -> result<bool, string>;
}

interface pairs {

  /// Returns the value of the resource. 
  put: func(choice: either, key: string, value: value) -> value;

  /// Returns the value of the resource. 
  /// Get a value from the given key, if it exists.
  /// Returns some value or None.
  get: func(choice: either, key: string) -> option<value>;

  /// Either current or proposed 
  enum either {
    /// The current kv pairs
    current,

    /// The proposed kv pairs 
    proposed
  }

  /// A binary value and associated hint 
  record binary {
    /// The binary value
    value: list<u8>,

    /// A hint for the binary value
    hint: string
  }

  /// A string value and associated hint 
  record str {
    /// The string value
    value: string,

    /// A hint for the string value
    hint: string
  }

  /// A variant representing the different types of values that can be stored.
  variant value {
    /// A binary value 
    binary(binary),

    /// A string value 
    str(str),

    /// Success value 
    success(u32),

    /// Failure value 
    failure(string)
  }
}

interface utils {
    /// Logs some output from the guest component.
    log: func(message: string);

    /// Get a random byte from the host system
    random-byte: func() -> u8;
}

/// The world interface for the VM component
world virtual-machine {

    import utils;

    /// Virtual machine needs get and put functions 
    

    /// Export the main api for the VM component
    export vm;
}
