[package]
name = "comrade-core"
version = "0.1.1"
edition = "2021"

[dependencies]
tracing = "0.1.40"
multikey = { version = "1.0", git = "https://github.com/cryptidtech/bs.git" }
multisig = { version = "^1.0", git = "https://github.com/cryptidtech/bs.git" }
multihash = { version = "1.0", git = "https://github.com/cryptidtech/bs.git" }
multiutil = { version = "1.0", git = "https://github.com/cryptidtech/bs.git" }
wasm_component_layer = { workspace = true }

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "color"] }
comrade-core = { path = "." }
hex = "0.4"
rand = "0.8"
multicodec = { version = "1.0", git = "https://github.com/cryptidtech/rust-multicodec.git" }
