[package]
name = "comrade"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*", "examples/*"]

[dependencies]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
