[workspace]
resolver = "2"
members = ["crates/*", "examples/*", "tests"]

[workspace.dependencies]
fusion = { path = "crates/fusion" }

[profile.release]
codegen-units = 1
opt-level = "z"
debug = false
strip = true
lto = true
