package component:unlock;

interface host {
    /// Pushes a key value pair onto the stack 
    push: func(key: string);
}

/// An example world for the component to target.
world example {
    import host;

    export unlock: func() -> bool;
}
