[package]
name = "comrade-rhai"
version = "0.1.0"
edition = "2024"

[dependencies]
comrade-core.workspace = true
rhai = { version = "1.19.0", features = ["only_i32", "sync"] }
tracing = "0.1.40"
parking_lot = "0.12.3"                                         # a more efficient Mutex library

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "color"] }
hex = "0.4"
rand = "0.8"
multicodec = { version = "1.0", git = "https://github.com/cryptidtech/rust-multicodec.git" }
